export const signup = async (req, res) => {
    try {
        
    } catch (error) {
        console.error(`Đã có lỗi: ${error}`);
    }
}